### ISSUE TITLE
kotlin 相比 java10

### ISSUE THREAD

**Issue by liseri** [heimashi/kotlin_tips#10]
你好，看了您的文章，写的非常好； 想请教下java10已经出来了，在正式项目中使用kotlin的好处还有多大。 以我仅写过helloword的经验看，比较喜欢data model和类似List.of的集合字面量，语法上确实简洁了些，但java中有lombok, java8有lambda, 函数式接口， java10又推出了var, 这些都大大的进了一步，在这种情况下想请教下团队要学习kotlin还有没有很有说服力的理由，尤其是kotlin的get set语法不太简洁

**Comment by heimashi** [comment]
我的感觉是kotlin处境比较尴尬，没有一个绝对的理由去使用它(例如别人不能做而只有它能做)，虽然有很多简洁新颖的语法(像kotlin的扩展属性和方法），在团队中去推行的话还是要看团队是否有足够的时间和对新语言的兴趣

**Comment by SaltedFish-Extreme** [comment]
@liseri 老哥现在还在用java吗😂
