### ISSUE TITLE
kotlin感觉就是语法糖而已。编译还是没有java快。

### ISSUE THREAD

**Issue by LiqiNew** [heimashi/kotlin_tips#3]

**Comment by mikilangkilo** [comment]
学kotlin最大的动力，难道不是招聘jd上面那行“熟练使用kotlin”吗？

**Comment by LiqiNew** [comment]
然而招聘上面并没有写上熟悉kotlin。一般都是精通java。

**Comment by heimashi** [comment]
升级gradle tools 3.0.1之后编译速度已经大幅提高了吧。毕竟是官方的语法糖，后续的优化应该不是问题

**Comment by LiqiNew** [comment]
除非不用JVM

**Comment by heimashi** [comment]
@LiqiNew 为什么有这样的结论？kotlin是直接编译成class，不需要先翻译成java后再编译成class，编译时间不会相差很多，参考比较老版本kotlin的[对比](https://medium.com/keepsafe-engineering/kotlin-vs-java-compilation-speed-e6c174b39b5d)，kotlin1.2版本也在编译上做了[优化](https://blog.jetbrains.com/kotlin/2017/11/kotlin-1-2-released/)

**Comment by SaltedFish-Extreme** [comment]
四年过去了，楼上现在还有继续用Java的吗😂

**Comment by LiqiNew** [comment]
楼主转行了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heimashi/kotlin_tips"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月2日(星期三) 晚上7:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [heimashi/kotlin_tips] kotlin感觉就是语法糖而已。编译还是没有java快。 (#3)





 
四年过去了，楼上现在还有继续用Java的吗😂
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SaltedFish-Extreme** [comment]
@LiqiNew 转行了可还行，老哥干嘛去了😂

**Comment by LiqiNew** [comment]
做跨境电商去了。混的还不如做开发。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heimashi/kotlin_tips"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [heimashi/kotlin_tips] kotlin感觉就是语法糖而已。编译还是没有java快。 (#3)





 
@LiqiNew 转行了可还行，老哥干嘛去了😂
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SaltedFish-Extreme** [comment]
还行，老哥再转回来啊😂

**Comment by LiqiNew** [comment]
再转回来你带我吗？要不转了这么多年，没有人带一下一下子还运转不开。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heimashi/kotlin_tips"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [heimashi/kotlin_tips] kotlin感觉就是语法糖而已。编译还是没有java快。 (#3)





 
还行，老哥再转回来啊😂
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SaltedFish-Extreme** [comment]
我太菜了，离职了之后还没找着工作，我就是看着第一行代码还有做些小项目出来的，老哥你也可以先找个小公司练练手😂

**Comment by LiqiNew** [comment]
明年可能要重出江湖了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heimashi/kotlin_tips"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [heimashi/kotlin_tips] kotlin感觉就是语法糖而已。编译还是没有java快。 (#3)





 
我太菜了，离职了之后还没找着工作，我就是看着第一行代码还有做些小项目出来的，老哥你也可以先找个小公司练练手😂
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SaltedFish-Extreme** [comment]
可以，加油(ง ˙o˙)ว
