### ISSUE TITLE
about 扩展函数不能被override

### ISSUE THREAD

**Issue by spff** [heimashi/kotlin_tips#6]
這樣算是可以被override嗎

```
class Inner{
}

open class Parent{
    open fun Inner.extendFunc3():String = ""
}

class Child:Parent(){
    override fun Inner.extendFunc3():String = "override"
}
```

**Comment by Cat7373** [comment]
并不算，有多个同名的扩展函数时，哪个在上下文中哪个就生效，并没有覆盖关系

**Comment by spff** [comment]
In Java, all non-static methods are by default "virtual functions." Only methods marked with the keyword final, which cannot be overridden, along with private methods, which are not inherited, are non-virtual.

能否override取決於是否為virtual ，然後上面的code轉成Java並沒看到static 或 final
(不過我無法使用super來呼叫Parent寫的Inner.extendFunc3就是了)

**Comment by spff** [comment]
看了[kotlin官網](https://kotlinlang.org/docs/reference/extensions.html)寫的大概知道tip4原本想表達的意思，不過覺得用官網的例子會更好懂一些
C().caller(D())   // prints "D.foo in C"
C1().caller(D())  // prints "D.foo in C1" - dispatch receiver is resolved virtually
C().caller(D1())  // prints "D.foo in C" - extension receiver is resolved statically

然後究其原因是因為在轉換的時候會overload成兩個function
```
   public void foo(@NotNull D $receiver) {
      Intrinsics.checkParameterIsNotNull($receiver, "$receiver");
      String var2 = "D.foo in C";
      System.out.println(var2);
   }

   public void foo(@NotNull D1 $receiver) {
      Intrinsics.checkParameterIsNotNull($receiver, "$receiver");
      String var2 = "D1.foo in C";
      System.out.println(var2);
   }
```

**Comment by heimashi** [comment]
@spff 感谢反馈，之前的表意的确有些不够恰当，已更新
