### ISSUE TITLE
我是掘金的香菜小编，我想邀请把这篇文章发到掘金。

### ISSUE THREAD

**Issue by ghost** [heimashi/kotlin_tips#8]
heimashi，你好。我是掘金的小编，在我的掘金昵称是：一颗香菜。我想邀请你把你的这篇 Kotlin_tips 发到掘金专栏，让更多开发者看到。这是我的个人微信：cx923373725 。如果你还有什么想要了解的，可以加我微信。

**Comment by heimashi** [comment]
你好，欢迎欢迎，欢迎转发哈！
